Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
map = None
b_popup = True

map = stations_polygon.explore(color="yellow", popup=b_popup)
map = buses_polygon.query("dc == False").explore(color="red", popup=b_popup, m=map)
map = buses_polygon.query("dc == True").explore(color="purple", popup=b_popup, m=map)
map = lines.query("v_nom <= 230").explore(color="green", popup=b_popup, m=map)
map = lines.query("(v_nom > 230) & (v_nom <= 330)").explore(
    color="orange", popup=b_popup, m=map
)
map = lines.query("(v_nom > 330) & (v_nom <= 420)").explore(
    color="darkred", popup=b_popup, m=map
)
map = lines.query("v_nom > 420").explore(color="pink", popup=b_popup, m=map)
map = links.explore(color="purple", popup=b_popup, m=map)
map = converters.explore(color="black", popup=b_popup, m=map)
map = transformers.explore(color="pink", popup=b_popup, m=map)
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/geopandas/explore.py:285[39m, in [36m_explore[39m[34m(df, column, cmap, color, m, tiles, attr, tooltip, popup, highlight, categorical, legend, scheme, k, vmin, vmax, width, height, categories, classification_kwds, control_scale, marker_type, marker_kwds, style_kwds, highlight_kwds, missing_kwds, tooltip_kwds, popup_kwds, legend_kwds, map_kwds, **kwargs)[39m
[32m    283[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mre[39;00m
[32m--> [39m[32m285[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mbranca[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[34;01mbc[39;00m
[32m    286[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mfolium[39;00m

[31mModuleNotFoundError[39m: No module named 'branca'

During handling of the above exception, another exception occurred:

[31mImportError[39m                               Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[11][39m[32m, line 4[39m
[32m      1[39m [38;5;28mmap[39m = [38;5;28;01mNone[39;00m
[32m      2[39m b_popup = [38;5;28;01mTrue[39;00m
[32m----> [39m[32m4[39m [38;5;28mmap[39m = [43mstations_polygon[49m[43m.[49m[43mexplore[49m[43m([49m[43mcolor[49m[43m=[49m[33;43m"[39;49m[33;43myellow[39;49m[33;43m"[39;49m[43m,[49m[43m [49m[43mpopup[49m[43m=[49m[43mb_popup[49m[43m)[49m
[32m      5[39m [38;5;28mmap[39m = buses_polygon.query([33m"[39m[33mdc == False[39m[33m"[39m).explore(color=[33m"[39m[33mred[39m[33m"[39m, popup=b_popup, m=[38;5;28mmap[39m)
[32m      6[39m [38;5;28mmap[39m = buses_polygon.query([33m"[39m[33mdc == True[39m[33m"[39m).explore(color=[33m"[39m[33mpurple[39m[33m"[39m, popup=b_popup, m=[38;5;28mmap[39m)

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/geopandas/geodataframe.py:2305[39m, in [36mGeoDataFrame.explore[39m[34m(self, *args, **kwargs)[39m
[32m   2303[39m [38;5;129m@doc[39m(_explore)
[32m   2304[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mexplore[39m([38;5;28mself[39m, *args, **kwargs):
[32m-> [39m[32m2305[39m     [38;5;28;01mreturn[39;00m [43m_explore[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43m*[49m[43margs[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/geopandas/explore.py:300[39m, in [36m_explore[39m[34m(df, column, cmap, color, m, tiles, attr, tooltip, popup, highlight, categorical, legend, scheme, k, vmin, vmax, width, height, categories, classification_kwds, control_scale, marker_type, marker_kwds, style_kwds, highlight_kwds, missing_kwds, tooltip_kwds, popup_kwds, legend_kwds, map_kwds, **kwargs)[39m
[32m    297[39m         [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mmatplotlib[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m cm
[32m    299[39m [38;5;28;01mexcept[39;00m ([38;5;167;01mImportError[39;00m, [38;5;167;01mModuleNotFoundError[39;00m):
[32m--> [39m[32m300[39m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[32m    301[39m         [33m"[39m[33mThe [39m[33m'[39m[33mfolium[39m[33m'[39m[33m, [39m[33m'[39m[33mmatplotlib[39m[33m'[39m[33m and [39m[33m'[39m[33mmapclassify[39m[33m'[39m[33m packages are required for [39m[33m"[39m
[32m    302[39m         [33m"[39m[33m'[39m[33mexplore()[39m[33m'[39m[33m. You can install them using [39m[33m"[39m
[32m    303[39m         [33m"[39m[33m'[39m[33mconda install -c conda-forge folium matplotlib mapclassify[39m[33m'[39m[33m [39m[33m"[39m
[32m    304[39m         [33m"[39m[33mor [39m[33m'[39m[33mpip install folium matplotlib mapclassify[39m[33m'[39m[33m.[39m[33m"[39m
[32m    305[39m     )
[32m    307[39m [38;5;66;03m# xyservices is an optional dependency[39;00m
[32m    308[39m [38;5;28;01mtry[39;00m:

[31mImportError[39m: The 'folium', 'matplotlib' and 'mapclassify' packages are required for 'explore()'. You can install them using 'conda install -c conda-forge folium matplotlib mapclassify' or 'pip install folium matplotlib mapclassify'.

